/** City suggestions for checkout — buyer still types freely. */
export const nepalCities: string[] = [
  "Kathmandu",
  "Lalitpur",
  "Bhaktapur",
  "Pokhara",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Butwal",
  "Dharan",
  "Hetauda",
  "Itahari",
  "Janakpur",
  "Nepalgunj",
  "Dhangadhi",
  "Bhairahawa",
  "Siddharthanagar",
  "Ghorahi",
  "Tulsipur",
  "Damak",
  "Birtamod",
  "Kirtipur",
  "Madhyapur Thimi",
  "Chitwan",
];
